name: Sheriff Apply

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  push:
    branches:
      - main
jobs:
  perm-sync:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: us.gcr.io/cncf-slack-infra/sheriff/sheriff:cncf-slack-plugin
      env:
        PERMISSIONS_FILE_ORG: cncf
        SHERIFF_HOST_URL: 'https://sheriff-ajrw3kq6ta-uc.a.run.app'
        SHERIFF_PLUGINS: cncfSlack
        PERMISSIONS_FILE_REPO: people
        SHERIFF_IMPORTANT_BRANCH: main
        GSUITE_CREDENTIALS: e30=
        SHERIFF_GITHUB_APP_CREDS: ${{ secrets.SHERIFF_GITHUB_APP_CREDS }}
        GITHUB_WEBHOOK_SECRET: ${{ secrets.SHERIFF_GITHUB_SECRET }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Sync permissions (For real)
        run: |
          cd /usr/src/app/lib/permissions && \
          touch .env.example && \
          node /usr/src/app/lib/permissions/run.js --do-it-for-real-this-time